### ISSUE TITLE
Greenbits 1.91 crashed two times

### ISSUE THREAD

**Issue by bitcoinuser** [greenaddress/GreenBits#161]
Greenbits 1.91 crashed two times. I sent the report to Google Store.

Did you see it?

Thanks.

**Comment by greenaddress** [comment]
Yes, one (or maybe even both of them not sure yet) should be already fixed since in 9062f01cc53d16ffcbcca4a87f4d8c38d8dd4c36

**Comment by jgriffiths** [comment]
Hi @bitcoinuser, The next release should fix this issue for you, it should be available in a couple of days. Please reopen this issue if you experience any further crashes.

**Comment by greenaddress** [comment]
@bitcoinuser we release r1.92 - if not already available it should be available soon on all stores.

**Comment by bitcoinuser** [comment]
Hi,

Updated. I think this greenbits version is the first one that doesn't crash.

What is in greenbits todo list?

Thanks.

**Comment by bitcoinuser** [comment]
Hi, I'm still reproducing a crash on version 1.92. I reported to Google store. Did you see?

Thanks.

**Comment by greenaddress** [comment]
Hi @bitcoinuser , we got it, thanks. Hoping to have it fixed by next release with a couple of library updates and overall minor improvements.
